In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv("./tariff_data_cleaned.csv")

In [3]:
dataframe.head(20)

,Country,US 2024 Deficit,US 2024 Exports,US 2024 Imports (Customs Basis),Trump Tariffs Alleged,Trump Response,Population
0,Afghanistan,-11.1,11.4,22.6,0.49,0.25,41454761.0
1,Albania,13.4,141.7,128.3,0.10,0.10,2745972.0
2,Algeria,-1447.1,1014.5,2461.6,0.59,0.29,46164219.0
3,Andorra,1.5,4.9,3.4,0.10,0.10,80856.0
4,Angola,-1186.9,682.4,1869.2,0.63,0.32,36749906.0
5,Anguilla,71.3,72.5,1.2,0.10,0.10,NaN
6,Antigua and Barbuda,550.0,573.8,23.8,0.10,0.10,93316.0
7,Argentina,2078.8,9171.0,7092.2,0.10,0.10,45538401.0
8,Armenia,39.2,160.8,121.6,0.10,0.10,2990900.0
9,Aruba,714.8,725.5,10.7,0.10,0.10,107359.0
10,Australia,17907.8,34593.3,16685.5,0.10,0.10,26658948.0
11,Azerbaijan,97.3,255.1,157.8,0.10,0.10,10153958.0
12,Bahamas,3847.4,5639.7,1792.4,0.10,0.10,399440.0
13,Bahrain,441.9,1646.2,1204.3,0.10,0.10,1577059.0
14,Bangladesh,-6151.8,2214.0,8365.8,0.74,0.37,171466990.0
15,Barbados,724.0,772.6,48.6,0.10,0.10,282336.0
16,Belarus,-9.4,10.6,20.0,0.47,0.24,9178298.0
17,Belize,509.3,590.4,81.1,0.10,0.10,411106.0
18,Benin,167.8,216.4,48.6,0.10,0.10,14111034.0
19,Bermuda,517.1,540.4,23.3,0.10,0.10,64698.0